baseURL = "https://ezh.es/"
languageCode = "en-us"
theme = "hugo-book"
paginate = 10
disableKinds = ['taxonomy', 'taxonomyTerm']
enableGitInfo = true

[params]
	contentTypeName = "posts"
	BookSection = 'posts'
	BookLogo = 'images/logo.svg'
  BookTheme = 'auto'

[markup.goldmark.renderer]
	# render in-line HTML
	unsafe= true 

[markup.tableOfContents]
  startLevel = 1

[permalinks]
	posts = "/:year/:month/:title/"

[languages]
	[languages.en]
		languageName = "English"
		title = "Ezhes"
